### ISSUE TITLE
High INP on link drag and click

### ISSUE THREAD

**Issue by Zdend** [GoogleChrome/web-vitals-extension#170]
**Describe the bug**
When anchor tags are dragged and clicked a few ms later, the extension reports a high INP.

**To Reproduce**
Go to any Single Page Application (non SPA works as well, it will just unload your page so it's harder to see), drag an anchor link as if you were about to bookmark it and then release pointer and actually click the link. High INP (300-400ms) will be reported even though there is barely any work on the event handler. Chrome Performance analysis report also highlights this as a problematic interaction with a long Input Delay. A long duration is also reported by PerformanceObserver event timing native to the browser.

**Expected behavior**
Dragging of links will not contribute to high INP, input delay seems to be native to the browser that allows the dragged link to return to its original position after mouse has been released and isn't any indication of poor site responsiveness. Users might accidentally trigger this if they move their mouse whilst clicking and lingering a big longer on the target element.

**Version:**

- OS w/ version: Mac OS 14.1
- Browser w/ version Chrome Version 121.0.6167.85 (Official Build) (arm64)

**Additional context, screenshots, screencasts**
![INP drag and click](https://github.com/GoogleChrome/web-vitals-extension/assets/8145571/b86035a4-a7ad-40f8-8a4f-5457963e489e)

<img width="813" alt="Screenshot 2024-02-01 at 2 02 42 pm" src="https://github.com/GoogleChrome/web-vitals-extension/assets/8145571/7bf1eccb-0e71-4178-b3d2-66628e3faf8b">

**Comment by rviscomi** [comment]
Thanks @Zdend but I think your concern is more about the way INP is actually measured, rather than an issue with the extension itself as I'm able to reproduce this on a page with the extension disabled:

<img width="867" alt="image" src="https://github.com/GoogleChrome/web-vitals-extension/assets/1120896/a55e9fca-7223-46fb-93e1-7adbad83cb35">

Would you mind raising this in a new thread on [web-vitals-feedback](https://groups.google.com/g/web-vitals-feedback)?
