### ISSUE TITLE
Address CPU usage concerns

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/web-vitals-extension#67]
Over the last few weeks, we have received a few reports about the extension consuming increased CPU when certain pages are open (in particular Google Meet) - this is generally due to these pages having a high CLS. This has been an issue we previously tried to tackle using badge update throttling. It helped some users, but we're still hearing this is an issue for others. What are our options?

## Option 1 ✋🏽

We consider adding an internal disallow list to the extension which skips badging URLs we deem to be sufficiently problematic (e.g meet.google.com). This would leave these tabs with a gray badge, similar to internal Chrome pages. I would only be comfortable doing this in the most egregious of cases. 

## Option 2 👀

Disable badging for a tab if we detect CLS update frequency is high (N updates in M time window) and looks like it will continue to be high. The benefit of this solution is that it's more general than 1 (...and would help with cases like [this](https://twitter.com/PKodmad/status/1270875710312177664) where Reddit appears to be the culprit). The other benefit is that you can still do some badging for a tab without disabling it outright. 

The downside is that a tab has to get close to behaving badly before we intervene, but we can tweak the time window to reduce the risk here.

@rviscomi @patrickhulce do you have any preferences on the above?

**Comment by patrickhulce** [comment]
I wonder if this is the extent of the issue. I too had to disable the extension a bit ago because it was hanging Chrome entirely, making the entire browser UI unresponsive to keypresses, scrolls, etc. This was even when I had no obvious culprits like meet.google.com. 

I'm loosely suspecting something else at play like attempting to listen to tabs that aren't active, leaks that create an ever growing set of listener callbacks or something like that, because I can't imagine just CLS events from my active tab could possibly bring Chrome to the crawl I was witnessing. My general usage pattern is lots of tabs and leaving Chrome open forever. That's pretty much the only repro case I can offer :/

Of these two though, I'd definitely agree to move toward Option 2 where the extension activity is throttled overall rather than specific site blocks 👍

**Comment by sprankhub** [comment]
## Option 3

Similar to other analytics extensions, do not analyse the page by default. Only analyse the page after the extension has been activated for a specific page (e.g. click on extension, click button "reload and measure").

**Comment by patrickhulce** [comment]
I like that a lot @sprankhub :) I *think* everything should still work with `buffered: true`

@addyosmani how do you feel about a click-to-compute model for the extension rather than trying to hunt down the demons lying here?

**Comment by addyosmani** [comment]
I would be open to click-to-compute but view it as a bit of a last resort... :) One of the benefits of our ambient badge is that it currently requires no developer interaction to get value out of it when you install and browse. 

Another downside of click-to-compute is that if I'm loading up a page and an element suddenly causes me to go into 'the red', this will be less clear if you are waiting on an interaction to enable reporting. Just my two cents.

I'm a little more excited about the idea of only badging the current active tab (and pausing/disabling badging on all other tabs until one returns to being in the forground)
