### ISSUE TITLE
Persist FID value between pages on HUD

### ISSUE THREAD

**Issue by gilbertococchi** [GoogleChrome/web-vitals-extension#76]
FID issues due to 3rd parties on click events are quite hard to troubleshoot so far and I am wondering if the web-vitals-extension HUD Overlay can store the previous page FID value to help spotting this kind of issues.

Below an example on Montblanc IT https://www.montblanc.com/it-it site where FID becomes 165ms but it's impossible for the user to notice that on the next page and it correlates with a 3rd party script Function Call.
![Screenshot 2020-10-21 at 10 57 57](https://user-images.githubusercontent.com/329023/96697514-4b9f1c80-138c-11eb-8ec1-a4085d5201e7.png)

**Comment by addyosmani** [comment]
This is an interesting feature request. If I'm reading this correctly, there is interest in adding History support to the extension so that, perhaps on navigation to a new page/route, we temporarily persist the set of CWV values previously experienced and perhaps give you some drill-down:

<details>
  <summary>Previous values</summary>
  <ul>
     <li>https://foo.com/about - LCP: 2.4s, FID: 0.3s, CLS: 0.4</li>
     <li>https://foo.com/contact - LCP: 2.6s, FID: 0.4s, CLS: </li>
  </ul>
</details>

Something like the above? If not could you clarify the request? I would also be interested in @rviscomi's thoughts here.

**Comment by gilbertococchi** [comment]
Exactly, having some way to browse/inspect previous values, especially FID would be beneficial considering the metric nature.

In the screenshot I've added you can tell that the Extension is on Page2 after having clicked on a button on Page1 but only thanks to the "Performance" session screenshots of the Page1 FID value being populated I was able to tell Page1 FID was of 165ms.

**Comment by rviscomi** [comment]
I filed https://github.com/GoogleChrome/web-vitals-extension/issues/77 for a different reason but I actually think it would solve this use case. Console logs can be persisted across navigations, so it should be straightforward to refer back to the previous page's FID.

I think the technical bar for console logs is really low, so that may be a lower friction way to achieve the same result without having to fit it into the UI somehow.

**Comment by gilbertococchi** [comment]
+1, great idea, I believe using some simple Console Logs would solve the gap here!
